---
- name: Check basic server info
  hosts: localhost
  connection: local
  gather_facts: yes

  tasks:
    - name: Display OS information
      debug:
        msg: "OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Display hostname
      debug:
        msg: "Hostname: {{ ansible_hostname }}"

    - name: Display IP address
      debug:
        msg: "IP address: {{ ansible_default_ipv4.address }}"

    - name: Display total memory
      debug:
        msg: "Total memory: {{ ansible_memtotal_mb }} MB"

    - name: Display number of CPUs
      debug:
        msg: "Number of CPUs: {{ ansible_processor_count }}"

    - name: Display disk usage
      shell: df -h /
      register: disk_usage
    - debug:
        msg: "Disk usage: {{ disk_usage.stdout_lines }}"
