---
- name: Update all Ubuntu machines
  hosts: localhost
  become: yes
  tasks:
    - name: Update and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_distribution == 'Ubuntu'
